project_id = "khvsudrwnqznuxnjurxp"

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-ticket-confirmation]
verify_jwt = false

[functions.send-ticket-status-update]
verify_jwt = false

[functions.send-email-otp]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-verification-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-whatsapp-call-notification]
verify_jwt = false

[functions.create-credit-purchase]
verify_jwt = false

[functions.create-one-time-payment]
verify_jwt = false

[functions.seed-profiles]
verify_jwt = false

[functions.send-whatsapp-otp]
verify_jwt = false

[functions.translate-message]
verify_jwt = false

[functions.send-missed-call-notification]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false
